version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    groups:
      actions-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    groups:
      gradle-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/camprofw/rust/fea-engine"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    groups:
      cargo-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    groups:
      pip-minor:
        update-types:
          - "minor"
          - "patch"
