name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feat', 'feature']
  - title: '🐛 Fixes'
    labels: ['fix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore']
  - title: '🧪 Tests'
    labels: ['test']
  - title: '📚 Documentation'
    labels: ['docs']
  - title: '♻️ Refactoring'
    labels: ['refactor']

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

exclude-labels:
  - 'skip-changelog'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor', 'feat', 'feature']
  patch:
    labels: ['fix', 'bug', 'chore', 'docs', 'refactor', 'test']
  default: patch

label-aliases:
  feat: ['feature']
  fix: ['bug']

template: |
  ## What’s Changed
  $CHANGES

  ---
  Scopes touched: $CONTRIBUTORS
