"""
Constants used throughout the CamProV5 codebase.

This module consolidates duplicate literals to ensure consistency
and make maintenance easier.
"""

# Material Properties
# Steel (typical gear material)
YOUNGS_MODULUS_STEEL = 200e9  # Pa (200 GPa)
POISSON_RATIO_STEEL = 0.3
YIELD_STRENGTH_STEEL = 400e6  # Pa (400 MPa)
ULTIMATE_STRENGTH_STEEL = 600e6  # Pa (600 MPa)
FATIGUE_LIMIT_STEEL = 200e6  # Pa (200 MPa)
DENSITY_STEEL = 7850.0  # kg/m³

# Default FEA Parameters
DEFAULT_YOUNGS_MODULUS = YOUNGS_MODULUS_STEEL
DEFAULT_POISSON_RATIO = POISSON_RATIO_STEEL
DEFAULT_YIELD_STRENGTH = YIELD_STRENGTH_STEEL
DEFAULT_ULTIMATE_STRENGTH = ULTIMATE_STRENGTH_STEEL
DEFAULT_FATIGUE_LIMIT = FATIGUE_LIMIT_STEEL
DEFAULT_DENSITY = DENSITY_STEEL

# Gear Design Constants
DEFAULT_MODULE = 2.0  # mm
DEFAULT_ADDENDUM = 2.0  # mm
DEFAULT_DEDENDUM = 2.5  # mm
DEFAULT_PRESSURE_ANGLE = 20.0  # degrees
DEFAULT_TOOTH_COUNT_MIN = 20
DEFAULT_TOOTH_COUNT_MAX = 100

# Safety Factors
DEFAULT_BENDING_SAFETY_FACTOR = 2.0
DEFAULT_CONTACT_SAFETY_FACTOR = 1.5
DEFAULT_FATIGUE_SAFETY_FACTOR = 1.8

# Contact Ratio Limits
CONTACT_RATIO_MIN = 1.0
CONTACT_RATIO_MAX = 2.5

# Gear Radius Limits
MIN_GEAR_RADIUS = 10.0  # mm
MAX_GEAR_RADIUS = 200.0  # mm

# Motion Law Parameters
DEFAULT_RING_ROTATION_DEG = 180.0
DEFAULT_COMPRESSION_DURATION_PERCENT = 70.0
DEFAULT_TDC_DWELL_DEG = 4.0
DEFAULT_BDC_DWELL_DEG = 3.0
DEFAULT_TDC_RAMP_BEFORE_DEG = 2.0
DEFAULT_TDC_RAMP_AFTER_DEG = 2.0
DEFAULT_BDC_RAMP_BEFORE_DEG = 20.0
DEFAULT_BDC_RAMP_AFTER_DEG = 20.0
DEFAULT_TDC_CONSTANT_VELOCITY_DEG = 40.0
DEFAULT_BDC_CONSTANT_VELOCITY_DEG = 40.0

# Performance Limits
DEFAULT_MAX_VELOCITY = 10.0  # m/s
DEFAULT_MAX_ACCELERATION = 100.0  # m/s²
DEFAULT_MAX_JERK = 1000.0  # m/s³

# Numerical Constants
EPSILON = 1e-12  # Small number for numerical stability
PI = 3.141592653589793
DEG_TO_RAD = PI / 180.0
RAD_TO_DEG = 180.0 / PI

# File Paths
DEFAULT_OUTPUT_DIR = "output"
DEFAULT_LOG_DIR = "logs"
DEFAULT_FIXTURES_DIR = "fixtures"

# String Constants
CAMPRO_VERSION = "5.0.0"
DEFAULT_ENCODING = "utf-8"
