blank_issues_enabled: false
contact_links:
  - name: Security policy
    url: https://github.com/maxholden/CamProV5/blob/main/SECURITY.md
    about: Please report security vulnerabilities responsibly using our Security Policy.
  - name: Support
    url: https://github.com/maxholden/CamProV5/blob/main/SUPPORT.md
    about: Questions or troubleshooting requests should go here when appropriate instead of opening an issue.
  - name: Questions and Discussions
    url: https://github.com/maxholden/CamProV5/discussions
    about: Please ask and answer questions here.
