name: Feature request
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
  - type: textarea
    id: context
    attributes:
      label: Additional context
