installRootName: github
expectedFiles:
  .shared-indexes:
    - index.info
  ij-shared-indexes-tool-cli:
    - bin/ijSharedIndexesTool
assets:
  - dir: .shared-indexes
    url: file:///Users/maxholden/Documents/GitHub/CamProV5/scripts/.smoke-shared-indexes/artifacts/shared.zip
    sha256: 042a033d7b1147bf1bb9577bb0bdb98d0134dba11cb4ef6a203903ae4c8b3f8a
  - dir: ij-shared-indexes-tool-data
    url: file:///Users/maxholden/Documents/GitHub/CamProV5/scripts/.smoke-shared-indexes/artifacts/tool-data.zip
    sha256: c3ed61276adc8acbba5c7ba7256597b15eceb6dda0d8d4bab7bd18a4cdf61752
  - dir: ij-shared-indexes-tool-cli
    url: file:///Users/maxholden/Documents/GitHub/CamProV5/scripts/.smoke-shared-indexes/artifacts/cli.zip
    sha256: 3154d0b80e96db9d699ff20615164cf9ab55ace2ac26fc2f87e31270a15cf56d
