installRootName: github
expectedFiles:
  .shared-indexes:
    - index.info
  ij-shared-indexes-tool-cli:
    - bin/ijSharedIndexesTool
assets:
  - dir: .shared-indexes
    url: file:///Users/maxholden/Documents/GitHub/CamProV5/scripts/.smoke-shared-indexes/artifacts/shared.zip
    sha256: 3fd5b315421f97f436de3582fda379f7512e3af0290e7dc861760b66c6b79468
  - dir: ij-shared-indexes-tool-data
    url: file:///Users/maxholden/Documents/GitHub/CamProV5/scripts/.smoke-shared-indexes/artifacts/tool-data.zip
    sha256: 985397e9a56dabd84152c3df904f2e210a86dbfcf52729f0e46e780784265418
  - dir: ij-shared-indexes-tool-cli
    url: file:///Users/maxholden/Documents/GitHub/CamProV5/scripts/.smoke-shared-indexes/artifacts/cli.zip
    sha256: 95c28c3f32ec676a195b9929036612f2ef1639016254b4b390145a8377a423be
